language: ruby

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.8.1-amd64.deb
  - sudo systemctl start elasticsearch.service

rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode
#  - rbx-2.1.1
